@startuml
[*] --> 未上班
未上班 --> 已签到上班 : 完成签到操作
已签到上班 --> 空闲待命 : 暂无患者就诊安排
空闲待命 --> 接诊患者 : 有患者前来就诊
接诊患者 --> 诊断中 : 开始询问病情等诊断工作
诊断中 --> 开具医嘱 : 完成病情诊断
开具医嘱 --> 安排检查 : 医嘱包含检查项目
安排检查 --> 等待检查结果 : 患者去做检查
等待检查结果 --> 复诊评估 : 检查结果返回
复诊评估 --> 修改医嘱 : 根据结果需调整医嘱
修改医嘱 --> 医嘱确认 : 完成医嘱修改与确认
医嘱确认 --> 治疗跟进 : 患者按医嘱进行治疗
治疗跟进 --> 患者出院 : 患者治疗完成出院
患者出院 --> 空闲待命 : 继续等待下一位患者
空闲待命 --> 已签退下班 : 到下班时间签退
已签退下班 --> [*]
@endum